import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/client/header";
import { SessionProvider } from "next-auth/react";
import Footer from "./components/client/footer";

export const metadata: Metadata = {
  title: "Hardware",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
