import type { Metadata } from "next";
import "@/src/app/globals.css";

import Header from "./components/server/header";
import Footer from "./components/client/footer";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { auth } from "../authOptions";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Hardware",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth(); // Fetch the session data
  return (
    <html
      lang="en"
      data-theme="bumblebee"
      className={cn("font-sans", inter.variable)}
    >
      <body>
        <Header session={session} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
