import type { Metadata } from "next";
import "@/src/app/globals.css";

import Header from "./components/server/header";
import { DM_Serif_Display } from "next/font/google";
const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  weight: ["400"],
});
import Footer from "./components/client/footer";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { auth } from "../authOptions";
import Link from "next/link";
import Search from "./components/client/search";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { Menu } from "lucide-react";
import LogoutButton from "./components/client/button/logoutButton";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Hardware",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const session = await auth(); // Fetch the session data
  return (
    <html
      lang="en"
      data-theme="bumblebee"
      className={cn("font-sans", inter.variable)}
    >
      <body>
        <section className="flex sticky top-0 z-10 bg-white justify-center w-full flex-col items-center px-4 md:px-8 h-16">
          <div className="max-w-7xl grid grid-cols-3 w-full justify-between items-center">
            <Link
              className={`text-2xl sm:text-3xl ${dmSerif.className} text-gray-600`}
              href={"/"}
            >
              Hardware
            </Link>
            <div className="  place-self-center">
              <Search />
            </div>
            <div className="dropdown sm:block place-self-end dropdown-end w-max h-max">
              <DropdownMenu>
                <DropdownMenuTrigger
                  className={" px-4 "}
                  render={<Button size={"lg"} className={"rounded-3xl "} />}
                >
                  <Menu size={32} strokeWidth={3} />
                </DropdownMenuTrigger>
                <DropdownMenuContent side="bottom">
                  <DropdownMenuGroup>
                    <DropdownMenuLabel>Account</DropdownMenuLabel>
                    {/* <DropdownMenuItem>Profile</DropdownMenuItem>
                  <DropdownMenuItem>Billing</DropdownMenuItem> */}

                    {!session || !session.user ? (
                      <>
                        <DropdownMenuItem>
                          <Link
                            href={"/login"}
                            scroll={false}
                            className="w-full"
                          >
                            Login
                          </Link>
                        </DropdownMenuItem>
                        <DropdownMenuItem>
                          <Link
                            href={"/signup"}
                            scroll={false}
                            className="w-full"
                          >
                            Sign up
                          </Link>
                        </DropdownMenuItem>
                      </>
                    ) : (
                      <>
                        <DropdownMenuItem>
                          <Link href={"/profile"}>Profile</Link>
                        </DropdownMenuItem>
                        <DropdownMenuItem>
                          <Link href={"/cart"}>Cart</Link>
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuGroup>
                          <LogoutButton />
                        </DropdownMenuGroup>
                      </>
                    )}
                  </DropdownMenuGroup>
                  {/* <DropdownMenuSeparator />
                <DropdownMenuGroup>
                  <DropdownMenuItem>Team</DropdownMenuItem>
                  <DropdownMenuItem>Subscription</DropdownMenuItem>
                </DropdownMenuGroup> */}
                </DropdownMenuContent>
              </DropdownMenu>
              {/* 
            <div
              tabIndex={0}
              role="button"
              className="btn btn-sm h-10 rounded-full bg-white "
            >
              <svg
                color="#374151"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
                className="size-6 "
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
                />
              </svg>
              {!session ? (
                <svg
                  color="#374151"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  fill="currentColor"
                  className="size-6"
                >
                  <path
                    fillRule="evenodd"
                    d="M18.685 19.097A9.723 9.723 0 0 0 21.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 0 0 3.065 7.097A9.716 9.716 0 0 0 12 21.75a9.716 9.716 0 0 0 6.685-2.653Zm-12.54-1.285A7.486 7.486 0 0 1 12 15a7.486 7.486 0 0 1 5.855 2.812A8.224 8.224 0 0 1 12 20.25a8.224 8.224 0 0 1-5.855-2.438ZM15.75 9a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z"
                    clipRule="evenodd"
                  />
                </svg>
              ) : (
                <Image
                  className="rounded-full"
                  src={session.user?.image ?? ""}
                  alt=""
                  height={20}
                  width={20}
                />
              )}
            </div>

            <ul
              tabIndex={0}
              className="dropdown-content shadow-lg menu bg-base-100 rounded-box z-1c w-52 p-2"
            >
              {session && session.user?.role === "admin" ? (
                <>
                  <AdminButton />
                </>
              ) : null}

              {!session || !session.user ? (
                <>
                  <LoginButton />
                </>
              ) : (
                <>
                  <li>
                    <Link href={"/profile"}>Profile</Link>
                  </li>
                  <li>
                    <Link href={"/cart"}>Cart</Link>
                  </li>
                </>
              )}
              {session && session.user ? (
                <>
                  <div className="divider m-0" />
                  <LogoutButton />
                </>
              ) : null}
            </ul> */}
            </div>
          </div>
        </section>
        {children}
        {modal}
        <Footer />
      </body>
    </html>
  );
}
