import type { Metadata } from "next";
import "@/src/app/globals.css";
import GlobalHeader from "../components/Headers/GlobalHeader";

export const metadata: Metadata = {
  title: "Hardware | Admin workspace",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <GlobalHeader />
      {children}
    </>
  );
}
